// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docSidebar: [
    {
      type: "doc",
      id: "index",
      label: "Introduction",
    },
    {
      type: "category",
      label: "Get started",
      collapsed: false,
      link: {
        type: "generated-index",
        slug: "/get-started",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "get-started",
        },
      ],
    },
    {
      type: "category",
      label: "How to",
      link: {
        type: "generated-index",
        slug: "/how-to",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "how-to",
        },
      ],
    },
    {
      type: "category",
      label: "Concepts",
      link: {
        type: "generated-index",
        slug: "/concepts",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "concepts",
        },
      ],
    },
    {
      type: "category",
      label: "Tutorials",
      link: {
        type: "generated-index",
        slug: "/tutorials",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "tutorials",
        },
      ],
    },
    {
      type: "category",
      label: "Reference",
      link: {
        type: "generated-index",
        slug: "/reference",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "reference",
        },
      ],
    },
    "chatbot"
  ],
};

module.exports = sidebars;
