// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docSidebar: [
    {
      type: "doc",
      id: "index",
      label: "Introduction",
    },
    {
      type: "category",
      label: "Get started",
      collapsed: false,
      link: {
        type: "generated-index",
        slug: "/get-started",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "get-started",
        },
      ],
    },
    {
      type: "category",
      label: "How to",
      link: {
        type: "generated-index",
        slug: "/how-to",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "how-to",
        },
      ],
    },
    {
      type: "category",
      label: "Concepts",
      link: {
        type: "generated-index",
        slug: "/concepts",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "concepts",
        },
      ],
    },
    {
      type: "category",
      label: "Tutorials",
      link: {
        type: "generated-index",
        slug: "/tutorials",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "tutorials",
        },
      ],
    },
    {
      type: "category",
      label: "Reference",
      link: {
        type: "generated-index",
        slug: "/reference",
      },
      items: [
        {
          type: "category",
          label: "Command line",
          link: {
            type: "generated-index",
            slug: "/reference/cli",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "reference/cli",
            },
          ],
        },
        {
          type: "doc",
          id: "reference/api/json-rpc",
          label: "JSON-RPC API",
        },
        {
          type: "category",
          label: "REST API",
          link: {
            type: "doc",
            id: "reference/api/rest",
          },
          items: [
            {
              type: "category",
              label: "Consensus layer",
              collapsed: true,
              link: {
                type: "generated-index",
                slug: "/reference/api/eth2",
              },
              items: [
                {
                  type: "autogenerated",
                  dirName: "reference/api/eth2",
                },
              ],
            },
            {
              type: "category",
              label: "Execution layer",
              collapsed: true,
              link: {
                type: "generated-index",
                slug: "/reference/api/eth1",
              },
              items: [
                {
                  type: "autogenerated",
                  dirName: "reference/api/eth1",
                },
              ],
            },
          ],
        },
        {
          type: "doc",
          id: "reference/key-config-file-params",
        },
        {
          type: "doc",
          id: "reference/security-disclosure",
        },
      ],
    },
    "chatbot"
  ],
};

module.exports = sidebars;
