name: IndexNow
on:
  schedule:
    - cron: '0 11 * * 0'
  workflow_dispatch:

jobs:
  indexnow:
    environment: analytics
    runs-on: ubuntu-latest
    steps:
      - name: Submit to IndexNow
        uses: bojieyang/indexnow-action@38ddfbd93579a8a44c0dee662121bf9d51098f71 # 3.0.0
        with:
          sitemap-location: 'https://docs.web3signer.consensys.io/sitemap.xml'
          key: ${{ secrets.INDEXNOW_APIKEY }}
          since: 7
          since-unit: 'day'
          lastmod-required: false