---
name: generate llm text

on:
  schedule:
    - cron: "0 22 * * 6"
  workflow_dispatch:

jobs:
  llms:
    
    name: Lint Code Base, Spelling
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:

      - uses: actions/checkout@v3

      - name: generate-llms
        uses: ConsenSys/github-actions/docs-firecrawl-llm@firecrawl
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FIRECRAWL_API_KEY: ${{ secrets.FIRECRAWL_API_KEY }}
          TARGET_URL: "https://docs.web3signer.consensys.io/development"
          MAX_URLS: 25
          SHOW_FULL_TEXT: true
